spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/novel_system?serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  servlet:
    multipart:
      max-file-size: 5MB
server:
  ip: localhost
  port: 9090
files:
  upload:
    path: D:/IdeaProjects/files/

Mybatia-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml